server:
  port: ${PORT}

spring:
  application:
    name: stream-backend

#  datasource:
#    url: ${DB_URL}
#    username: root
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  management:
    endpoints:
      web:
        exposure:
          include: health


  datasource:
    url: jdbc:mysql://${STREAM_HOST}:${STREAM_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${STREAM_USERNAME}
    password: ${STREAM_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  web:
    resources:
      static-locations: file:media/

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

stripe:
  secret-key: ${STRIPE_KEY}
cors:
  allowed-origins:
    - "http://localhost:4200"
    - "http://dfpybtxmxgkxr.cloudfront.net"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed-headers:
    - "*"

jwt:
  secret: "secret-key"
  expiration: 3600000
